# 服务器端口
server:
  port: 8080
spring:
  # 应用名称
  application:
    name: security-demo
  # 数据源
  datasource:
    username: root
    password: zhu23789
    url: jdbc:mysql://47.106.145.145:3306/security?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  # jpa配置
  jpa:
    show-sql: false #数据库操作时显示sql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #数据库平台
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    com.ys.adage.mapper: INFO
    org.springframework: INFO
